# Generated by Django 5.1.6 on 2025-03-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address1',
            new_name='shipping_address',
        ),
    ]
