# Generated by Django 5.1.6 on 2025-03-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_number',
            field=models.CharField(max_length=6, verbose_name='R8uwBo'),
        ),
    ]
