# Generated by Django 5.1.6 on 2025-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicshop', '0003_alter_product_stock_number_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_number',
            field=models.CharField(max_length=6, verbose_name='wFrfnj'),
        ),
    ]
